name: Run Command

on: [push]

jobs:
  run-command:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9  # Specify the desired Python version

    - name: Run Command
      shell: bash
      run: SHELL=/bin/bash make run-command
